default:
    suites:
        default:
            contexts:
                - Test\Application\Behat\Context\DemoContext
            paths: ["../test/Application/Features"]

    extensions:
        FriendsOfBehat\SymfonyExtension: null
