index:
    path: /
    controller: App\Controller\DefaultController
    methods: ['GET']

create_user:
    path: /users
    controller: App\Controller\User\UserController::create
    methods: ['POST']

get_user:
    path: /users/{id}
    controller: App\Controller\User\UserController::get
    methods: ['GET']
